-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 14:07:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



USE `reseau_social` ;

DROP TABLE IF EXISTS `reseau_social`.`users` ;

DROP TABLE IF EXISTS `reseau_social`.`albums` ;

DROP TABLE IF EXISTS `reseau_social`.`friends` ;

DROP TABLE IF EXISTS `reseau_social`.`groups` ;

DROP TABLE IF EXISTS `reseau_social`.`pictures` ;

DROP TABLE IF EXISTS `reseau_social`.`posts` ;

DROP TABLE IF EXISTS `reseau_social`.`usersgroup` ;

DROP TABLE IF EXISTS `reseau_social`.`share` ;


CREATE TABLE IF NOT EXISTS `reseau_social`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `hashedPassword` VARCHAR(255) NOT NULL,
  `profilPicture` VARCHAR(255) DEFAULT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
  )ENGINE = InnoDB;


INSERT INTO 
`users`(`email`, `login`, `hashedPassword`, `profilPicture`, `firstname`, `lastname`)
VALUES
('alain@gmail.com', 'alain78', '123456', NULL, 'Alain', 'Chambort'),
('guillaume@gmail.com', 'guillaume78', '123456', NULL, 'Guillaume', 'Augier'),
('magalie@gmail.com', 'magalie78', '123456', NULL, 'Magalie', 'Petit'),
('oceane@gmail.com', 'oceane78', '123456', NULL, 'Océane', 'Legaz'),
('stephanie@gmail.com', 'stephanie78', '123456', NULL, 'stephanie', 'Joly'),
('isabelle@gmail.com', 'isabelle78', '123456', NULL, 'isabelle', 'Brune'),
('jerome@gmail.com', 'jerome78', '123456', NULL, 'Jerome', 'Rey'),
('laure@gmail.com', 'laure78', '123456', NULL, 'ola', 'Bigot');



CREATE TABLE IF NOT EXISTS `reseau_social`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `albums_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `reseau_social`.`users` (`id`)
    )ENGINE = InnoDB;


INSERT INTO `albums` (`name`, `user_id`)
VALUES ('familial', 1), ('sportif', 2), ('vacances', 3);




CREATE TABLE IF NOT EXISTS `reseau_social`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `user2_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `friends_user_2`
    FOREIGN KEY (`user2_id`)
    REFERENCES `reseau_social`.`users` (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `reseau_social`.`users` (`id`)
    )ENGINE = InnoDB;

INSERT INTO `friends`(`user_id`, `user2_id`)
VALUES
(1,2);


CREATE TABLE IF NOT EXISTS `reseau_social`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `groups_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `reseau_social`.`users` (`id`)
    )ENGINE = InnoDB;

INSERT INTO `groups` (`name`, `user_id`)
VALUES 
('la famille en or', 1), 
('les sportifs', 2), 
('les vacanciers', 3);



CREATE TABLE IF NOT EXISTS `reseau_social`.`pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `pictures_album_id`
    FOREIGN KEY (`album_id`)
    REFERENCES `reseau_social`.`albums` (`id`)
    )ENGINE = InnoDB;

INSERT INTO `pictures`(`path`, `name`, `album_id`)
VALUES
(NULL, 'Annecy', 3),
(NULL, 'Tour de france', 2),
(NULL, 'pique-nique', 1); 




CREATE TABLE IF NOT EXISTS `reseau_social`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NULL,
  `body` VARCHAR(250) NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`)
  )ENGINE = InnoDB;


INSERT INTO `posts` (`title`, `body`, `date`)
VALUES
( NULL, NULL, now() );



CREATE TABLE IF NOT EXISTS `reseau_social`.`share` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `user_id` INT NULL,
  `album_id` INT NULL,
  `post_id` INT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `share_album_id`
    FOREIGN KEY (`album_id`)
    REFERENCES `reseau_social`.`albums` (`id`),
  CONSTRAINT `share_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `reseau_social`.`groups` (`id`),
  CONSTRAINT `share_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `reseau_social`.`posts` (`id`),
  CONSTRAINT `share_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `reseau_social`.`users` (`id`)
    )ENGINE = InnoDB;


INSERT INTO `share` (`date`, `user_id`, `album_id`, `post_id`, `group_id`)
VALUES
(NULL, NULL, NULL, NULL, 1);



CREATE TABLE IF NOT EXISTS `reseau_social`.`usersGroup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usersGroup_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `reseau_social`.`groups` (`id`),
  CONSTRAINT `usersGroup_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `reseau_social`.`users` (`id`)
    )ENGINE = InnoDB;



INSERT INTO `usersGroup` (`user_id`, `group_id`)
VALUES
(1 , 1);